AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description:
    Lambda get from DDB Table
Resources:
  Lambdagetrecord:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Runtime: python3.9.10
      Environment:
        Variables:
          Dynamodbtable: !Ref DynamoDBTable
      Events:
        http:
          Type: Api
          Properties:
            Method: get
            Path: /
      Handler: lambdagetrecord.lambda_handler
      PackageType: Zip
      Policies:
        - Statement:
        - Sid: DDBDescribeTablePolicy
          Effect: Allow
          Action:
          - dynamodb:DescribeTable
          Resource: !GetAtt 'DynamoDBTable.Arn'
  DynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: "ID"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "ID"
          KeyType: "HAawsSH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      

Outputs:
  APIEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  TableName:
    Description: "Name of the DynamoDB table"
    Value: !Ref DynamoDBTable
